Implement ekfac with new interface
aai-institute/pyDVL pull request #476
Opened 2023-12-20 12:34 UTC by Xuzzo

### Description

This PR closes #460 

### Changes

- 

### Checklist

- [ ] Wrote Unit tests (if necessary)
- [ ] Updated Documentation (if necessary)
- [ ] Updated Changelog
- [ ] If notebooks were added/changed, added boilerplate cells are tagged with `"tags": ["hide"]` or `"tags": ["hide-input"]`

2023-12-21 09:59 UTC, schroedk commented on notebooks/influence_wine.ipynb
> +    "plt.plot(mean_ekfac_train_influences, color=\"red\")\n",
My suggestion would be to use a scatter plot instead, so one could see the correlation immediately.

2024-01-02 19:06 UTC, schroedk requested changes

2024-01-02 19:06 UTC, schroedk commented on src/pydvl/influence/torch/influence_function_model.py
> +    """
My suggestion would be to make all the methods related to the details of ekfac invisible in the documentation, i.e. add an underscore (make them "private").
If you really want to expose them to the user, my suggestion would be to make the docstrings complete, i.e. with input and output description in google format.

2024-01-02 19:06 UTC, schroedk commented on src/pydvl/influence/torch/util.py
> +    probs_ = torch.softmax(model_output, dim=1)
Please add a docstring to this function, maybe explaining the *args and **kwargs?

2024-01-02 20:28 UTC, Xuzzo commented on docs/assets/pydvl.bib
> +@article{george2018fast,
I'll add it in the notebook. It does not add much from the theory perspective, it is just focussed on LLMs

2024-01-02 20:29 UTC, Xuzzo commented on docs/influence/influence_function_model.md
> +if_model.update_diag(train_loader)
No updating the diagonal is optional. In most cases it improves things quite little and it takes as much time as fitting the k-fac blocks.

2024-01-03 12:48 UTC, Xuzzo commented on src/pydvl/influence/torch/util.py
> +        evecs_a_dict = {layer_name: evec_a for layer_name, (_, evec_a, _, _) in self}
I would keep it public. I have added some docs. Let me know if more needed

2024-01-04 10:11 UTC, schroedk commented on src/pydvl/influence/torch/influence_function_model.py
> +        self,
Still, having this separate method could be avoided. Is my understanding correct, that this is the eigenvalue correction (so the E in Ekfac?). I would suggest to introduce an init parameter, if the kfac blocks should be adapted to this update logic. What do you think?

2024-01-04 11:59 UTC, mdbenito commented
@Xuzzo Remember to add the paper to the readme!

2024-01-08 13:14 UTC, merged